name: Satis
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-satis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer config
        run: composer config --no-interaction allow-plugins.composer/satis true
      - uses: dev-this/satis-build@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: set git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: commit generated satis files
        run: |
          git add .
          git commit -m "update dependencies"
          git push